name: realtimeweather
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #state managment
  get: ^4.6.5

  #google
  json_serializable: ^6.1.5
  json_annotation: ^4.7.0

  #lottie
  lottie: ^1.4.2

  #network
  vexana: ^3.0.1

  #date
  intl: ^0.17.0

  

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  #dart dev
  build_runner: ^2.2.1

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/lottie/

